[project]
name = "avi-sens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.4",
 "beautifulsoup4>=4.12.0",
 "pydantic>=2.11.7",
]
